import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import NavBar from "@/components/NavBar";
import CustomScrollbar from "@/components/CustomScrollbar";
import LoaderOverlay from "@/components/LoaderOverlay";
import SmartLoader from "@/components/SmartLoader";
import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import ConditionalFooter from "@/components/ConditionalFooter";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoaderOverlay />
        <AuthProvider>
          <CartProvider>
            <SmartLoader />
            <CustomScrollbar />
            <NavBar />
            <Toaster />
            {children}
            <ConditionalFooter />
          </CartProvider>
        </AuthProvider>
        <Script 
          src="https://assets.calendly.com/assets/external/widget.js"
          strategy="afterInteractive"
        />
        
      </body>
      
    </html>
  );
}
