import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import NavBar from "@/components/NavBar";
import CustomScrollbar from "@/components/CustomScrollbar";
import LoaderOverlay from "@/components/LoaderOverlay";
import SmartLoader from "@/components/SmartLoader";
import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import ConditionalFooter from "@/components/ConditionalFooter";
import { Toaster } from "@/components/ui/sonner"
import { DOMErrorBoundary } from "@/components/DOMErrorBoundary"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener('error', function(e) {
                if (e.error && e.error.message && 
                    (e.error.message.includes('insertBefore') || 
                     e.error.message.includes('removeChild') ||
                     e.error.message.includes('appendChild'))) {
                  e.preventDefault();
                  console.warn('DOM manipulation error suppressed:', e.error.message);
                  return false;
                }
              });
              
              window.addEventListener('unhandledrejection', function(e) {
                if (e.reason && e.reason.message && 
                    (e.reason.message.includes('insertBefore') || 
                     e.reason.message.includes('removeChild') ||
                     e.reason.message.includes('appendChild'))) {
                  e.preventDefault();
                  console.warn('DOM manipulation error suppressed (promise):', e.reason.message);
                  return false;
                }
              });
              
              // Override console.error to catch DOM errors
              const originalConsoleError = console.error;
              console.error = function(...args) {
                const message = args.join(' ');
                if (message.includes('insertBefore') || 
                    message.includes('removeChild') ||
                    message.includes('appendChild')) {
                  console.warn('DOM manipulation error suppressed:', message);
                  return;
                }
                originalConsoleError.apply(console, args);
              };
            `,
          }}
        />
        <LoaderOverlay />
        <DOMErrorBoundary>
          <AuthProvider>
            <CartProvider>
              <SmartLoader />
              <CustomScrollbar />
              <NavBar />
              <Toaster />
              {children}
              <ConditionalFooter />
            </CartProvider>
          </AuthProvider>
        </DOMErrorBoundary>
        <Script 
          src="https://assets.calendly.com/assets/external/widget.js"
          strategy="afterInteractive"
        />
        
      </body>
      
    </html>
  );
}
